# Generated by Django 2.1.1 on 2018-09-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('m_ID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('m_url', models.CharField(max_length=200)),
                ('m_title', models.CharField(max_length=200)),
                ('m_time', models.DateTimeField()),
                ('m_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('m_word', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('m_article', models.ManyToManyField(to='searchEngine.Article')),
            ],
        ),
    ]
